Models/ErrorViewModel.cs
using System;

namespace Quotes_App.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Quote.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Quotes_App.Models
{
    public class Quote
    {
        [Key]
        [Required]
        public int QuoteId { get; set; }
        [Required]
        public string QuoteText { get; set; }
        [Required]
        public string AuhtorFname { get; set; }
        [Required]
        public string AuthorLname { get; set; }
        public string Subject { get; set; }
        public string Cite { get; set; }
    }
}

Models/QuoteDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace Quotes_App.Models
{
    public class QuoteDbContext : DbContext
    {
        public QuoteDbContext(DbContextOptions<QuoteDbContext> options) : base(options)
        {
            //enure that the context db is really created
            Database.EnsureCreated();
        }

        public DbSet<Quote> Quote { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Quotes_App.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Quotes_App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/QuotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Quotes_App.Models;

namespace Quotes_App.Controllers
{
    public class QuotesController : Controller
    {
        private readonly QuoteDbContext _context;

        public QuotesController(QuoteDbContext context)
        {
            _context = context;
        }

        // GET: Quotes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Quote.ToListAsync());
        }

        // GET: Quotes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quote = await _context.Quote
                .FirstOrDefaultAsync(m => m.QuoteId == id);
            if (quote == null)
            {
                return NotFound();
            }

            return View(quote);
        }

        // GET: Quotes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Quotes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("QuoteId,QuoteText,AuhtorFname,AuthorLname,Subject,Cite")] Quote quote)
        {
            if (ModelState.IsValid)
            {
                _context.Add(quote);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(quote);
        }

        // GET: Quotes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quote = await _context.Quote.FindAsync(id);
            if (quote == null)
            {
                return NotFound();
            }
            return View(quote);
        }

        // POST: Quotes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("QuoteId,QuoteText,AuhtorFname,AuthorLname,Subject,Cite")] Quote quote)
        {
            if (id != quote.QuoteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(quote);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuoteExists(quote.QuoteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(quote);
        }

        // GET: Quotes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quote = await _context.Quote
                .FirstOrDefaultAsync(m => m.QuoteId == id);
            if (quote == null)
            {
                return NotFound();
            }

            return View(quote);
        }

        // POST: Quotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var quote = await _context.Quote.FindAsync(id);
            _context.Quote.Remove(quote);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuoteExists(int id)
        {
            return _context.Quote.Any(e => e.QuoteId == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>View some great quotes from some great people.</p>
</div>
<br />
<br />
<div class="text-center">
    <h1>Like this guy</h1>
    <img src="~/Kenobi.gif" alt="Kenobi GIF" />
</div>

Views/Quotes/Create.cshtml
@model Quotes_App.Models.Quote

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Please add to our wonderful collection of quotes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="QuoteText" class="control-label">Quote</label>
                <input asp-for="QuoteText" class="form-control" />
                <span asp-validation-for="QuoteText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuhtorFname" class="control-label">Author First Name</label>
                <input asp-for="AuhtorFname" class="form-control" />
                <span asp-validation-for="AuhtorFname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorLname" class="control-label">Author Last Name</label>
                <input asp-for="AuthorLname" class="form-control" />
                <span asp-validation-for="AuthorLname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject" class="control-label">Subject</label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cite" class="control-label">Citation</label>
                <input asp-for="Cite" class="form-control" />
                <span asp-validation-for="Cite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Quotes/Delete.cshtml
@model Quotes_App.Models.Quote

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Quote</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuoteText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuoteText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuhtorFname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuhtorFname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorLname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorLname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cite)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="QuoteId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Quotes/Details.cshtml
@model Quotes_App.Models.Quote

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Quote</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuoteText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuoteText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuhtorFname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuhtorFname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorLname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorLname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cite)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.QuoteId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Quotes/Edit.cshtml
@model Quotes_App.Models.Quote

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Quote</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="QuoteId" />
            <div class="form-group">
                <label asp-for="QuoteText" class="control-label"></label>
                <input asp-for="QuoteText" class="form-control" />
                <span asp-validation-for="QuoteText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuhtorFname" class="control-label"></label>
                <input asp-for="AuhtorFname" class="form-control" />
                <span asp-validation-for="AuhtorFname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorLname" class="control-label"></label>
                <input asp-for="AuthorLname" class="form-control" />
                <span asp-validation-for="AuthorLname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cite" class="control-label"></label>
                <input asp-for="Cite" class="form-control" />
                <span asp-validation-for="Cite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Quotes/Index.cshtml
@model IEnumerable<Quotes_App.Models.Quote>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Quote
            </th>
            <th>
                Author First Name
            </th>
            <th>
                Author Last Name
            </th>
            <th>
                Subject
            </th>
            <th>
                Citation
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.QuoteText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuhtorFname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuthorLname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cite)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.QuoteId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.QuoteId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.QuoteId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Quote Collection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Quotes Collection</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quotes" asp-action="Create">Add a Quote</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quotes" asp-action="Index">Quote Collection</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Quotes_App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>